name: Build MSYS2

on: [push]

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: base-devel
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: tools/msys2-setup.sh --install-all --noconfirm
      - name: Build
        run: |
          mkdir build && cd build
          cmake -G Ninja -DFETCH_lua=Yes ..
          ninja
          ninja test
          ninja wireshark_nsis_prep
          ninja wireshark_nsis
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nsis-installer
          path: build/packaging/nsis/wireshark-*-x64.exe

  install-nsis:
    runs-on: windows-latest
    needs: msys2-ucrt64
    steps:
      - name: Download installer
        uses: actions/download-artifact@v4
        with:
          name: nsis-installer
          path: downloads
      - name: Run installer
        working-directory: downloads
        run: |
          Get-ChildItem -Path wireshark-*-x64.exe | ForEach-Object {
            Start-Process $_.FullName -ArgumentList '/S /D=C:\Wireshark' -Wait
          }
      - name: Show version
        run: C:\Wireshark\wireshark.exe --version

